import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import "@/app/style/Card.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div >
        <ul className="nav1">
        <li><Link href="/pages/index">Home </Link></li>
        <li><Link href="/pages/blog">Blogs </Link></li>
        <li><Link href="/pages/about">About </Link></li>
        <li><Link href="/pages/contact">Contact </Link></li>
        </ul>
      </div>
      {children}</body>
    </html>
  )
}
